version: '3.8'

services:
  app-config-demo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - TEST_SETTING=Hello from Docker!
      - TEST_SECRET=MySecretValue123
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/config"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
